Listen 25120

<VirtualHost 127.0.0.1:25120>
    ServerName jedi.msya.gov.tt
    DocumentRoot /var/www/html/hosp_2025/public
    
    <Directory /var/www/html/hosp_2025/public>
        AllowOverride All
        Require all granted
        Options FollowSymLinks
    </Directory>
    
    ErrorLog /var/log/httpd/hosp_2025_error.log
    CustomLog /var/log/httpd/hosp_2025_access.log combined
</VirtualHost>